stages:
  - build
  - test
  - deploy

.build_website:
  image: node:22-alpine3.21
  stage: build
  script: 
    - yarn install 
    - yarn lint
    - yarn test
    - yarn build
  artifacts:
    paths:
      - build

.check_index:
  image: node:22-alpine3.21
  stage: test
  script:
    - yarn global add serve 
    - apk add curl
    - serve -s build &
    - sleep 10
    - curl http://localhost:3000 | grep "React App"

deploy_to_s3:
  stage: deploy
  image: 
    name: amazon/aws-cli:2.27.48
    entrypoint: [""]
  script:
    - aws --version
    - echo "Hello Poorna Raavi" > test.txt
    - aws s3 cp test.txt s3://$AWS_S3_BUCKET/test.txt


