stages:
  - build
  - package

variables:
  APP_VERSION: $CI_PIPELINE_IID
build_website:
  image: node:22-alpine3.21
  stage: build
  script: 
    - yarn install 
    - yarn lint
    - yarn test
    - yarn build
    - echo $APP_VERSION > build/version.html
  # artifacts saves the build directory. 
  # These saved ae passed to subsequent jobs in later stages
  artifacts:
    paths:
      - build

build docker image:
  stage: package
  image: docker:20.10.12 #Tells GitLab to run your job inside a docker container:20.10.12
  services:
    - docker:20.10.12-dind 
    #Starts up a separate service container that runs the actual Docker engine(daemon). 
    #This allows the main job container to connect to it & build images
  script:
  # this docker client is able to talk to docker deamon.
  # This looks for Dockerfile in project & builds a docker image
    - docker build -t $CI_REGISTRY_IMAGE -t $CI_REGISTRY_IMAGE:$APP_VERSION.
    - docker image ls #lists all the docker images available
