stages:
  - build
  - test

build_website:
  image: node:22-alpine3.21
  stage: build
  script: 
    - yarn install 
    - yarn build
  artifacts:
    paths:
      - build

linter:
  image: node:22-alpine3.21
  stage: test
  script:
    - yarn install
    - yarn lint


check_index:
  image: node:22-alpine3.21
  stage: test
  script:
    - yarn global add serve 
    - apk add curl
    - serve -s build &
    - sleep 10
    - curl http://localhost:3000 | grep "React App"

run_tests:
  image: node:22-alpine3.21
  stage: .pre
  script:
    - yarn install
    - yarn test