stages:
  - build
  - test
  - deploy staging
  - test staging
  - deploy
  - post deploy

variables:
  APP_BASE_URL: http://poorna-03072025.s3-website.us-east-2.amazonaws.com
  APP_BASE_URL_STAGING: http://poorna-03072025-staging.s3-website.us-east-2.amazonaws.com

build_website:
  image: node:22-alpine3.21
  stage: build
  script: 
    - yarn install 
    - yarn lint
    - yarn test
    - yarn build
  artifacts:
    paths:
      - build

check_index:
  image: node:22-alpine3.21
  stage: test
  script:
    - yarn global add serve 
    - apk add curl
    - serve -s build &
    - sleep 10
    - curl http://localhost:3000 | grep "React App"


deploy_to_stagging:
  stage: deploy staging
  image: 
    name: amazon/aws-cli:2.27.48
    entrypoint: [""]
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    - aws --version
    - echo $CI_COMIT_REF_NAME
    - aws s3 sync build s3://$AWS_S3_BUCKET_STAGING --delete

staging_tests:
  stage: test staging
  image: curlimages/curl:8.14.1
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    - curl $APP_BASE_URL_STAGING| grep "React App" 



deploy_to_production:
  stage: deploy
  image: 
    name: amazon/aws-cli:2.27.48
    entrypoint: [""]
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    - aws --version
    - echo $CI_COMIT_REF_NAME
    - aws s3 sync build s3://$AWS_S3_BUCKET --delete

production_tests:
  stage: post deploy
  image: curlimages/curl:8.14.1
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    - curl $APP_BASE_URL| grep "React App" 



