stages:
  - build
  - test

build_website:
  image: node:22-alpine3.21
  stage: build
  script: 
    - yarn install 
    - yarn build
  artifacts:
    paths:
      - build


check_index:
  image: alpine
  stage: test
  script:
    - test -f build/index.html

run_tests:
  image: node:22-alpine3.21
  stage: test
  script:
    - yarn install
    - yarn test